export const icons = {
  clock: require('./clock.png'),
  countDown: require('./count-down.png'),
  timer: require('./timer.png'),
  expand: require('./expand.png'),
  rotate: require('./rotate.png'),
  home: require('./home.png'),
  timerClock: require('./timer-clock.png'),
  alarmClock: require('./alarmClock.png'),
  moveUp: require('./move-up.png'),
  moveDown: require('./move-down.png'),
  downBtn: require('./down-button.png'),
  time: require('./time.png'),
  time2: require('./time2.png'),
  stop: require('./stop.png'),
  paused: require('./paused.png'),
  nightMode: require('./night-mode.png'),
};
